// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoPropio.data;

#nullable disable

namespace ProyectoPropio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240909023314_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProyectoPropio.Models.Dias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeOfTheDayId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AnimeOfTheDayId");

                    b.ToTable("dias");
                });

            modelBuilder.Entity("ProyectoPropio.Models.Historial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("historial");
                });

            modelBuilder.Entity("ProyectoPropio.Models.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualEpisode")
                        .HasColumnType("int");

                    b.Property<int?>("DiasId")
                        .HasColumnType("int");

                    b.Property<int?>("HistorialId")
                        .HasColumnType("int");

                    b.Property<int?>("HistorialIdDropeados")
                        .HasColumnType("int");

                    b.Property<int?>("HistorialIdProximos")
                        .HasColumnType("int");

                    b.Property<int?>("HistorialIdTerminados")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<string>("ListType")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NetflixURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TotalOfEpisode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiasId");

                    b.HasIndex("HistorialId");

                    b.HasIndex("HistorialIdDropeados");

                    b.HasIndex("HistorialIdProximos");

                    b.HasIndex("HistorialIdTerminados");

                    b.ToTable("series");
                });

            modelBuilder.Entity("ProyectoPropio.Models.Dias", b =>
                {
                    b.HasOne("ProyectoPropio.Models.Serie", "AnimeOfTheDay")
                        .WithMany()
                        .HasForeignKey("AnimeOfTheDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimeOfTheDay");
                });

            modelBuilder.Entity("ProyectoPropio.Models.Serie", b =>
                {
                    b.HasOne("ProyectoPropio.Models.Dias", null)
                        .WithMany("Historial")
                        .HasForeignKey("DiasId");

                    b.HasOne("ProyectoPropio.Models.Historial", "Historial")
                        .WithMany()
                        .HasForeignKey("HistorialId");

                    b.HasOne("ProyectoPropio.Models.Historial", null)
                        .WithMany("Dropeados")
                        .HasForeignKey("HistorialIdDropeados")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoPropio.Models.Historial", null)
                        .WithMany("Proximos")
                        .HasForeignKey("HistorialIdProximos")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoPropio.Models.Historial", null)
                        .WithMany("Terminados")
                        .HasForeignKey("HistorialIdTerminados")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("ProyectoPropio.Models.Dias", b =>
                {
                    b.Navigation("Historial");
                });

            modelBuilder.Entity("ProyectoPropio.Models.Historial", b =>
                {
                    b.Navigation("Dropeados");

                    b.Navigation("Proximos");

                    b.Navigation("Terminados");
                });
#pragma warning restore 612, 618
        }
    }
}
